### ISSUE TITLE
CatController Store Function

### ISSUE THREAD

**Issue by Technopathic** [rebeccavl/SRL-Backend#1]
Hi Rebecca,

I see that you're adding images to your categories. That's a good idea, maybe more work, but a good idea.
Checking to see if a user is an admin before creating a new category is also smart. 
A quick note, line 26:
`user = Auth::user();`
should be:
`$user = Auth::user();`
Since variables in PHP use the '$' identifier.

Line 32:
`$category = new category;`
Should be:
`$category = new Category;`
Since Models are capitalized. 

Aside from that, everything else looks fine. Keep it up.

**Comment by rebeccavl** [comment]
Thanks for reviewing.
